version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "7890:7890"
    volumes: 
      - "//d/programming/.bashrc:/root/.bashrc"